{
 "title": "Hardware - Dell - Detail",
 "description": "hardware-detail",
 "tags": [ "hardware-detail" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "location_server",
    "label": "location_server",
    "query": "label_values(      globalSystemStatus{ job=\"snmp-dell-hardware\" }  ,location_server) "
   },
   {
    "name": "func_server",
    "label": "func_server",
    "query": "label_values( globalSystemStatus{ job=\"snmp-dell-hardware\" ,location_server=\"$location_server\"},func_server)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values( globalSystemStatus{ job=\"snmp-dell-hardware\" ,location_server=\"$location_server\" ,func_server=\"$func_server\"},instance)"
   },
   {
    "name": "serverServiceTag",
    "label": "serverServiceTag",
    "query": "label_values( serverServiceTag{ job=\"snmp-dell-hardware\" ,instance=~\"$instance\"},serverServiceTag)"
   },
   {
    "name": "ip_address",
    "label": "ip_address",
    "query": "label_values( serverServiceTag{ job=\"snmp-dell-hardware\" ,instance=~\"$instance\"},ip_address)"
   },
   {
    "name": "rack",
    "label": "rack",
    "query": "label_values( serverServiceTag{ job=\"snmp-dell-hardware\" ,instance=~\"$instance\"},rack)"
   },
   {
    "name": "unit",
    "label": "unit",
    "query": "label_values( serverServiceTag{ job=\"snmp-dell-hardware\" ,instance=~\"$instance\"},unit)"
   }
  ]
 },
 "panels": [
  { "title": "Status: $serverServiceTag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "singlestat",
   "description": "- Service Tag: $serverServiceTag\n- Function: $func_server \n- IP address: $ip_address\n- Management: $instance\n- Location: $location_server.$rack.U$unit",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "globalSystemStatus{instance=\"$instance\"}",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemPowerState{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "PROCESSOR ISSUES (CPU)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "systemStateProcessorDeviceStatusCombined{instance=\"$instance\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "MEMORY ISSUES (RAM)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "systemStateMemoryDeviceStatusCombined{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "DISK ISSUES",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(physicalDiskComponentStatus{instance=\"$instance\"}!=3) or vector(0)",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "RAID status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(controllerRollUpStatus{instance=\"$instance\"})/count(controllerRollUpStatus{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAID BATTERY",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "systemStateBatteryStatusCombined{instance=\"$instance\"}",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "FAN status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStateCoolingDeviceStatusCombined{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power 1 - Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{instance=\"$instance\", powerSupplyIndex=\"1\"}"
    }
   ]
  },
  {
   "title": "Netw Dev",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(networkDeviceConnectionStatus{instance=\"$instance\"}>4) or vector(0)"
    }
   ]
  },
  {
   "title": "serviceTag",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "serverServiceTag{instance=\"$instance\"}",
     "legendFormat": "{{serverServiceTag}}"
    }
   ]
  },
  {
   "title": "BIOS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "systemBIOSStatus{instance=\"$instance\"}",
     "legendFormat": "Unhealthy"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(processorDeviceIndex{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "CORES",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(processorDeviceCoreCount{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(memoryDeviceSize{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
   "format": "kbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(memoryDeviceSize{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(physicalDiskComponentStatus{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Storage size",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(physicalDiskCapacityInMB{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Temp status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStateTemperatureStatusCombined{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CoolingUnit ",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "systemStateCoolingUnitStatusCombined{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Power 2 - Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "powerSupplyStatus{instance=\"$instance\", powerSupplyIndex=\"2\"}"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "amperageProbeReading{instance=\"$instance\"} > 20"
    }
   ]
  },
  { "title": "Detail Info:  $ip_address", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Inlet temp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 6 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "(temperatureProbeReading{instance=\"$instance\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeLocationName=~\".*Inlet.*\",instance=\"$instance\"})*0",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Controller Device (RAID)",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "controllerRollUpStatus{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": " Network devices $ip_address",
   "type": "table",
   "description": "$ip_address",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "0*networkDeviceConnectionStatus{instance=\"$instance\",networkDeviceProductName=~\".*Intel.*Ethernet.*\"}+ on (networkDeviceNumber) group_left(networkDeviceStatus) (networkDeviceStatus{instance=\"$instance\"})"
    },
    {
     "expr": "networkDeviceConnectionStatus{instance=\"$instance\",networkDeviceProductName=~\".*Intel.*Ethernet.*\"}"
    }
   ]
  },
  {
   "title": "CPU temperature",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(temperatureProbeReading{instance=\"$instance\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeLocationName=~\"CPU.*\",instance=\"$instance\"})*0",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": " Cooling devices (FAN)",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 11 },
   "targets": [
    {
     "expr": "coolingDeviceStatus{instance=\"$instance\"}"
    },
    {
     "expr": "0*coolingDeviceStatus{instance=\"$instance\"}+ on (coolingDeviceNumber) group_left(coolingDeviceReading) (coolingDeviceReading{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Server temperature sensors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "(temperatureProbeReading{instance=\"$instance\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{instance=\"$instance\"})",
     "legendFormat": "{{temperatureProbeLocationName}}"
    },
    {}
   ]
  },
  {
   "title": "Exhaust temp",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "(temperatureProbeReading{instance=\"$instance\"}/10) + on (temperatureProbeIndex) group_left(temperatureProbeLocationName) (temperatureProbeLocationName{temperatureProbeLocationName=~\".*Exhaust.*\",instance=\"$instance\"})*0",
     "legendFormat": "{{temperatureProbeLocationName}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(memoryDeviceSize{instance=\"$instance\"})  "
    }
   ]
  },
  {
   "title": "Hard drive details",
   "type": "table",
   "gridPos": { "h": 9, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "expr": "(physicalDiskCapacityInMB{instance=\"$instance\"}) + on (physicalDiskNumber) group_left(physicalDiskDisplayName) (physicalDiskDisplayName{instance=\"$instance\"}) + on (physicalDiskNumber) group_left(physicalDiskProductID) (physicalDiskProductID{instance=\"$instance\"})  + on (physicalDiskNumber) group_left(physicalDiskSerialNo) (physicalDiskSerialNo{instance=\"$instance\"}) "
    },
    {
     "expr": "physicalDiskComponentStatus{instance=\"$instance\"}"
    }
   ]
  }
 ]
}