{
 "title": "Hardware - Overview",
 "tags": [
  "hardware",
  "overview",
  "hardware-overview"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "location_server",
    "label": "location_server",
    "query": "label_values(      globalSystemStatus{ job=\"snmp-dell-hardware\" }  ,location_server) "
   }
  ]
 },
 "panels": [
  {
   "title": "HEALTH",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 0 },
   "content": "\n\n<a><img src=\"https://cdn4.iconfinder.com/data/icons/small-n-flat/24/heart-64.png\" width=auto height=\"105\" ></a> "
  },
  {
   "title": "HEALTH",
   "type": "table",
   "gridPos": { "h": 7, "w": 20, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(globalSystemStatus) (globalSystemStatus{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "Monitoring",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(up{job=\"snmp-dell-hardware\"})"
    }
   ]
  },
  {
   "title": "Cannot scrape",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(up{job=\"snmp-dell-hardware\"}==0)"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 7 },
   "content": "\n\n<a><img src=\"https://cdn3.iconfinder.com/data/icons/basicolor-computer-tech/24/106_power_turn_on-64.png\" width=auto height=\"105\" ></a> "
  },
  {
   "title": "SERVER OFF",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 7 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemPowerState) (systemPowerState{location_server=~\"$location_server\"}))!=4"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "content": "\n\n<a><img src=\"https://cdn0.iconfinder.com/data/icons/computer-and-hardware-free/32/Computer__Computer_Hardware_CPU_Processor_Technology-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 11 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStateProcessorDeviceStatusCombined) (systemStateProcessorDeviceStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 15 },
   "content": "\n<a><img src=\"https://cdn0.iconfinder.com/data/icons/computer-and-hardware-free/32/Computer__Computer_Hardware_RAM_Storage_Device_Memory_-64.png\" width=auto height=\"110\" ></a> ",
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 15 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStateMemoryDeviceStatusCombined) (systemStateMemoryDeviceStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "DISK",
   "type": "text",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 19 },
   "content": "<a><img src=\"https://cdn0.iconfinder.com/data/icons/computer-and-hardware-free/32/Computer__Computer_Hardware_Harddisk_Storage_Harddrive-128.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "DISK",
   "type": "table",
   "gridPos": { "h": 7, "w": 22, "x": 2, "y": 19 },
   "targets": [
    {
     "expr": " (physicalDiskComponentStatus{location_server=~\"$location_server\"})>3"
    }
   ]
  },
  {
   "title": "RAID",
   "type": "text",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 26 },
   "content": "<a><img src=\"https://cdn2.iconfinder.com/data/icons/sports-and-games-44/66/72-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "RAID",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 26 },
   "targets": [
    {
     "expr": " controllerRollUpStatus{location_server=~\"$location_server\"}>3",
     "legendFormat": "{{rack}}.U{{unit}}"
    }
   ]
  },
  {
   "title": "RAID BATT",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 34 },
   "content": "<a><img src=\"https://cdn4.iconfinder.com/data/icons/leto-devices-1/64/battery_accumulator-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "RAID BATT",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 34 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStateProcessorDeviceStatusCombined) (systemStateProcessorDeviceStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "POWER",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 38 },
   "content": "<a><img src=\"https://cdn1.iconfinder.com/data/icons/computer-hardware-594/64/09.COOLING_SYSTEM-Computer-_Cooler-_Cooling-_Cpu-_Fan-_Heatsink-_System-Hardware-System-Unit-Pc-Desktop--64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "COOLING UNIT",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 38 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStateCoolingUnitStatusCombined) (systemStateCoolingUnitStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "FAN",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 42 },
   "content": "<a><img src=\"https://cdn0.iconfinder.com/data/icons/computer-and-hardware-free/32/Computer__Computer_Hardware_Fan_Cooling_Cooler-256.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "FAN",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 42 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStateCoolingDeviceStatusCombined) (systemStateCoolingDeviceStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "PowerSupplyUnit",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 46 },
   "content": "<a><img src=\"https://cdn1.iconfinder.com/data/icons/computer-hardware-594/64/02.POWER_SUPPLY-Hardware-_Power-_Supply-_Unit-System-Unit-Pc-Desktop-_-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "PowerSupplyUnit",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 46 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStatePowerUnitStatusCombined) (systemStatePowerUnitStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "PowerSupply",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 50 },
   "content": "<a><img src=\"https://cdn0.iconfinder.com/data/icons/computer-and-hardware-free/32/Computer__Computer_Hardware_Plug_Electronic_Power_Cord-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "PowerSupply",
   "type": "table",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 50 },
   "targets": [
    {
     "expr": "(0*serverServiceTag{location_server=~\"$location_server\"}+ on (instance) group_left(systemStatePowerSupplyStatusCombined) (systemStatePowerSupplyStatusCombined{location_server=~\"$location_server\"}))!=3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 54 },
   "content": "<a><img src=\"https://cdn3.iconfinder.com/data/icons/computer-hardware-598/66/45_network_port_ethernet_internet_socket_lan_lan_port_computer_port_computer_port_icon_internet_line_icon-64.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "Netw",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 54 },
   "targets": [
    {
     "expr": " networkDeviceStatus{location_server=~\"$location_server\"}!=3"
    }
   ]
  },
  {
   "title": "Network",
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 59 },
   "content": "<a><img src=\"https://cdn0.iconfinder.com/data/icons/weather-888/32/weather_temperature_thermometer_cold_winter-256.png\" width=auto height=\"110\" ></a> "
  },
  {
   "title": "Netw",
   "type": "table",
   "gridPos": { "h": 5, "w": 22, "x": 2, "y": 59 },
   "targets": [
    {
     "expr": " systemStateTemperatureStatusCombined{location_server=~\"$location_server\"}!=3"
    }
   ]
  }
 ]
}